// <auto-generated />
using AsiaFridges.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsiaFridges.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240827170455_inintial")]
    partial class inintial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FridgeManagementSystemAsia.Models.FridgeType", b =>
                {
                    b.Property<int>("FridgeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeTypeID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FridgeTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FridgeTypeID");

                    b.ToTable("FridgeTypes");

                    b.HasData(
                        new
                        {
                            FridgeTypeID = 1,
                            DisplayOrder = 1,
                            FridgeTypeName = "Top Freezer"
                        },
                        new
                        {
                            FridgeTypeID = 2,
                            DisplayOrder = 2,
                            FridgeTypeName = "Bottom Freezer"
                        },
                        new
                        {
                            FridgeTypeID = 3,
                            DisplayOrder = 3,
                            FridgeTypeName = "Side-by-Side"
                        },
                        new
                        {
                            FridgeTypeID = 4,
                            DisplayOrder = 4,
                            FridgeTypeName = "Mini Fridge"
                        },
                        new
                        {
                            FridgeTypeID = 5,
                            DisplayOrder = 5,
                            FridgeTypeName = "Wine Cooler"
                        },
                        new
                        {
                            FridgeTypeID = 6,
                            DisplayOrder = 6,
                            FridgeTypeName = "Bar Fridge"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
